### PR TITLE
[python] fix 2018 nonprompt em channel

### PR DESCRIPTION
**Pull request by tihsu99**

### CODE REVIEW

**Comment by gourangakole** [comment]
Thanks @AlbertHsuNTUphys 

That looks reasonable me 
Did you check already how much yield is different? 

@efeyazgan please check.

**Comment by gourangakole** [comment]
just from Skype:
Terry: ----> 

``Hi @ZhengGang85129  please also check the PR, I'm not sure whether the trigger is right now.``

**Comment by gourangakole** [comment]
@ZhengGang85129

**Comment by tihsu99** [comment]
I haven't check the yield, this information should be on the AN already since Zhenggan independently produce yield table with correct trigger. Wrong Trigger yield 956.2(from limit plot preFit), Right Trigger yield 1011.5(from yield table). In addition, I think there is a bit random process when we do nonprompt estimation.

**Comment by tihsu99** [comment]
The randomness comes from when we separate MC training model, it randomly choose 50% of it and will affect the remain part when we do the MC substraction. T
he number should not be large since basically this yield mainly comes from data.

**Comment by ZhengGang85129** [comment]
Hi all, the trigger condition looks fine to me.

**Pull request merged**
